apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-rest-api
  namespace: go-rest-api
  labels:
    app: go-rest-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: go-rest-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
