apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-rest-api.fullname" . }}-secrets
  labels:
    {{- include "go-rest-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWTSecret: {{ .Values.secrets.jwtSecret | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  REDIS_URL: {{ .Values.secrets.redisURL | quote }}
